import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e1",
        "surface-tint": "#fabd00",
        "primary-fixed-dim": "#fabd00",
        "on-primary-fixed-variant": "#5b4300",
        "surface-dim": "#131313",
        "error": "#ffb4ab",
        "secondary-container": "#ff8f00",
        "on-surface-variant": "#d0c5af",
        "surface-container-lowest": "#0e0e0e",
        "outline": "#99907c",
        "on-secondary-container": "#623400",
        "tertiary-fixed-dim": "#e5beb5",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-fixed-variant": "#5c403a",
        "on-tertiary-fixed": "#2b1611",
        "surface-container-highest": "#353534",
        "on-primary-container": "#594100",
        "primary-container": "#e2aa00",
        "on-surface": "#e5e2e1",
        "secondary": "#ffb77a",
        "secondary-fixed-dim": "#ffb77a",
        "outline-variant": "#4d4635",
        "secondary-fixed": "#ffdcc2",
        "background": "#131313",
        "on-tertiary": "#432a25",
        "on-secondary": "#4c2700",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#6d3a00",
        "tertiary-container": "#d0aaa2",
        "error-container": "#93000a",
        "inverse-on-surface": "#313030",
        "primary": "#D4AF37",
        "primary-fixed": "#ffdf9e",
        "inverse-surface": "#e5e2e1",
        "on-primary": "#3f2e00",
        "tertiary-fixed": "#ffdad2",
        "surface": "#131313",
        "surface-variant": "#353534",
        "surface-container": "#201f1f",
        "surface-bright": "#3a3939",
        "tertiary": "#edc5bc",
        "on-tertiary-container": "#5a3e38",
        "on-error": "#690005",
        "on-secondary-fixed": "#2e1500",
        "inverse-primary": "#785900",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-playfair)", "Noto Serif", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
        serif: ["var(--font-noto-serif)", "serif"],
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.8s ease forwards",
        "fade-in": "fade-in 1.2s ease forwards",
      },
    },
  },
  plugins: [],
};
export default config;
